version: '3.8'
services:
  bot:
    build: .
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      OZON_CLIENT_ID: ${OZON_CLIENT_ID}
      OZON_API_KEY: ${OZON_API_KEY}
    restart: unless-stopped

